services:
  - type: web
    name: nexa-erp
    env: node
    plan: free
    buildCommand: |
      pnpm i --frozen-lockfile=false || npm i
      cd frontend
      pnpm i --frozen-lockfile=false || npm i
      pnpm build || npm run build
      cd ../backend
      pnpm i --frozen-lockfile=false || npm i
      pnpm prisma:generate || npx prisma generate
      pnpm build || npm run build
    startCommand: |
      cd backend
      pnpm migrate:deploy || npm run migrate:deploy
      node dist/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexa-erp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: nexa-erp-db
    plan: free
