services:
  - type: web
    name: nexa-erp-api
    env: node
    plan: free
    buildCommand: |
      cd backend
      pnpm i --frozen-lockfile=false || npm i
      pnpm prisma:generate || npx prisma generate
      pnpm build || npm run build
    startCommand: |
      cd backend
      pnpm migrate:deploy || npm run migrate:deploy
      node dist/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexa-erp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: static
    name: nexa-erp-frontend
    buildCommand: |
      cd frontend
      pnpm i --frozen-lockfile=false || npm i
      pnpm build || npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://nexa-erp-api.onrender.com

databases:
  - name: nexa-erp-db
    plan: free