services:
  - type: web
    name: nexa-erp
    env: node
    plan: free
    buildCommand: |
      cd frontend
      pnpm i --frozen-lockfile=false || npm i
      pnpm build || npm run build
      cd ../backend
      pnpm i --frozen-lockfile=false || npm i
      pnpm prisma:generate || npx prisma generate
      pnpm build || npm run build
    startCommand: |
      # arrancamos desde la raíz del repo
      if [ ! -d "./frontend/dist" ] && [ -d "./frontend" ]; then
        echo "Frontend dist not found. Building at runtime..."
        cd frontend
        pnpm i --frozen-lockfile=false || npm i
        pnpm build || npm run build
        cd ..
      fi
      cd backend
      pnpm prisma:generate || npx prisma generate
      pnpm db:push || npx prisma db push
      node dist/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexa-erp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: nexa-erp-db
    plan: free
